# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Check out GitHub repository"
      uses: actions/checkout@v3
    - name: "Use Node.js 16"
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install

    # Execute Juice Shop on our runner; we can then get ZAP going to
    # scan the running Juice Shop service
    #
    - name: "Execute Juice Shop"
      run: npm start & # Browse to http://localhost:3000
      
    # Get and run ZAP (unauthenticated, baseline scan)
    #
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.7.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        docker_name: 'owasp/zap2docker-stable'
        target: 'http://localhost:3000'
